### ISSUE TITLE
Log Into Account

### ISSUE THREAD

**Issue by aghodges** [vcu-cmsc355-f17/android-app-tbd#12]
As a returning user,
So that I can use the app,
I want to log into my account with my email and password.

**Comment by lowkeyhuy** [comment]
Test Name: Check Login Dialogue Box Exists
Given I am a opening the app and want to sign in to my account
When I click the "Sign-In" buton
Then a box containing usernames should appear.

**Comment by lowkeyhuy** [comment]
Test Name: Check Login Successful (account selection prompt)
Given I want to choose an account to sign into
When I click the sign-in button
Then an account selection box should appear.

**Comment by lowkeyhuy** [comment]
Test Name: Unsuccessful Log-In
Given I want to choose an account to sign into
When I select a username and enter the wrong password
Then I should not be logged into that username's account.

**Comment by lowkeyhuy** [comment]
Test Name: Account Selection Prompt Appears
Given I want to select an account to log into,
When I click the sign-in button,
A dialogue box should appear containing a list of accounts to choose from.
