### ISSUE TITLE
Make an Account

### ISSUE THREAD

**Issue by lowkeyhuy** [vcu-cmsc355-f17/android-app-tbd#5]
As a new user,
So that I can use the app,
I want to create an account to provide my personal information.

**Comment by nickagliano** [comment]
Given I opening the app and I'm not signed in
Then I should be on a screen with two options: "Create New Account" or "Sign in"
Given I select "Create New Account"
Then I should be on the "Create New Account" Screen
Given I am on the "Create New Account" Screen
When I enter my username and password
And my username is not taken by another user already
Then I should be brought to the homepage with a welcome message saying, "Welcome home, 'Username'"

**Comment by nickagliano** [comment]
Given I opening the app and I'm not signed in
Then I should be on a screen with two options: "Create New Account" or "Sign in"
Given I select "Create New Account"
Then I should be on the "Create New Account" Screen
Given I am on the "Create New Account" Screen
When I enter my username and password
And my username has already been taken by another user
Then I should receive a message saying that, 'Username", is already taken, please try another
Given I enter a new username that isn't taken
Then I should be brought to the homepage with a welcome message saying, "Welcome home, 'Username'"

**Comment by nickagliano** [comment]
Given I opening the app and I'm not signed in
Then I should be on a screen with two options: "Create New Account" or "Sign in"
Given I select "Create New Account"
Then I should be on the "Create New Account" Screen
Given I am on the "Create New Account" Screen
When I enter my username, email, and password
And my **email** has already been taken by another user
Then I should receive a message saying that, **"email"**, is already taken by another user, please try another
Given I enter a new **email** that isn't taken
Then I should be brought to the homepage with a welcome message saying, "Welcome home, 'Username'"
