### ISSUE TITLE
Grant the App Permissions

### ISSUE THREAD

**Issue by lowkeyhuy** [vcu-cmsc355-f17/android-app-tbd#8]
As a new user,
So that I can allow the app to know my current location,
I want to grant the app permissions to access the GPS and WiFi settings.

**Comment by nickagliano** [comment]
Given I opening the app and I haven't already given permissions
Then I should receive a request to access Location Services and WiFi permissions
When I allow permissions
Then I should be able to add a house and use other house functionalities

**Comment by nickagliano** [comment]
Given I am opening the app and I haven't already given permissions
Then I should receive a request to access Location Services and WiFi permissions
When I **do not** allow permissions
and when I try to add a house or use other house functionities
Then I should receive a message saying "You have not allowed permissions, would you like to allow access to Location Services and WiFi permissions?"
When I select yes
Then I should be able to add a house and use other house functionalities

**Comment by nickagliano** [comment]
Given I am opening the app and I haven't already given permissions
Then I should receive a request to access Location Services and WiFi permissions
When I do not allow permissions
and when I try to add a house or use other house functionities
Then I should receive a message saying "You have not allowed permissions, would you like to allow access to Location Services and WiFi permissions?"
When I select no
Then I should not be able to add a house and use other house functionalities

**Comment by lowkeyhuy** [comment]
Given I am opening the app and I have already given permissions
When I enter the home/login screen
Then I should NOT receive a request to access Location Services and WiFi permissions
